const READY_TO_START = "READY_TO_START";

const QUERY_COMPANY = "QUERY_COMPANY";

const QUERY_ROLE = "QUERY_ROLE";

const COMPANY_CONFIRMED = "COMPANY_CONFIRMED";

const CANCEL_SHIFT = "CANCEL_SHIFT";

module.exports = {
  READY_TO_START,
  QUERY_COMPANY,
  COMPANY_CONFIRMED,
  CANCEL_SHIFT
}
